"""
Management command to seed the database with sample categories and products.
Run: python manage.py seed_products
"""

from django.core.management.base import BaseCommand
from products.models import Category, Product


class Command(BaseCommand):
    help = 'Create sample categories and beverage products for development.'

    def handle(self, *args, **options):
        # Create categories
        cold, _ = Category.objects.get_or_create(
            slug='cold-drinks',
            defaults={'name': 'Cold Drinks', 'description': 'Chilled beverages', 'order': 1}
        )
        soft, _ = Category.objects.get_or_create(
            slug='soft-drinks',
            defaults={'name': 'Soft Drinks', 'description': 'Carbonated and non-alcoholic soft drinks', 'order': 2}
        )
        wines, _ = Category.objects.get_or_create(
            slug='wines',
            defaults={'name': 'Wines', 'description': 'Red, white, rosé, and sparkling wines', 'order': 3}
        )
        tea, _ = Category.objects.get_or_create(
            slug='tea',
            defaults={'name': 'Tea', 'description': 'Hot and iced teas from around the world', 'order': 4}
        )
        coffee, _ = Category.objects.get_or_create(
            slug='coffee',
            defaults={'name': 'Coffee', 'description': 'Premium coffee beans and brewed coffee', 'order': 5}
        )

        products_data = [
            # Cold drinks
            {
                'category': cold,
                'name': 'Iced Green Tea',
                'slug': 'iced-green-tea',
                'brand': 'House Blend',
                'price': 478.80,
                'description': 'Refreshing iced green tea with a hint of citrus.',
                'ingredients': 'Green tea, water, lemon, honey.',
                'history': 'Iced tea became popular in the US in the early 20th century. Green tea has been consumed in Asia for millennia.',
                'country_of_origin': 'USA',
                'featured': True,
            },
            {
                'category': cold,
                'name': 'Sparkling Lemonade',
                'slug': 'sparkling-lemonade',
                'brand': 'Fresh Press',
                'price': 538.80,
                'description': 'Carbonated lemonade with natural lemon juice.',
                'ingredients': 'Carbonated water, lemon juice, sugar, natural flavors.',
                'history': 'Lemonade has been enjoyed since medieval times. Sparkling versions gained popularity in the 19th century.',
                'country_of_origin': 'USA',
                'featured': True,
            },
            {
                'category': cold,
                'name': 'Iced Black Coffee',
                'slug': 'iced-black-coffee',
                'brand': 'Morning Roast',
                'price': 318.80,
                'description': 'Strong, chilled black coffee served over ice.',
                'ingredients': 'Coffee, water, ice.',
                'history': 'Cold coffee drinks became popular in the late 20th century as coffee culture expanded worldwide.',
                'country_of_origin': 'Italy',
            },
            {
                'category': cold,
                'name': 'Lemon Iced Tea',
                'slug': 'lemon-iced-tea',
                'brand': 'House Blend',
                'price': 334.80,
                'description': 'Sweet lemon iced tea with black tea base.',
                'ingredients': 'Black tea, water, sugar, lemon.',
                'history': 'Iced tea with lemon is a classic summer drink in North America and Europe.',
                'country_of_origin': 'USA',
            },
            {
                'category': cold,
                'name': 'Mint Lime Cooler',
                'slug': 'mint-lime-cooler',
                'brand': 'Fresh Press',
                'price': 358.80,
                'description': 'Refreshing cooler with lime juice and fresh mint.',
                'ingredients': 'Water, lime juice, sugar, mint leaves, ice.',
                'history': 'Mint and lime drinks have been served in tropical regions for centuries as a way to beat the heat.',
                'country_of_origin': 'India',
            },
            {
                'category': cold,
                'name': 'Berry Smoothie',
                'slug': 'berry-smoothie',
                'brand': 'Fresh Blend',
                'price': 478.80,
                'description': 'Thick blended drink with mixed berries and yogurt.',
                'ingredients': 'Strawberries, blueberries, raspberries, yogurt, honey, ice.',
                'history': 'Smoothies became popular in the late 20th century as part of the health food movement.',
                'country_of_origin': 'USA',
            },
            {
                'category': cold,
                'name': 'Watermelon Juice',
                'slug': 'watermelon-juice',
                'brand': 'Summer Press',
                'price': 310.80,
                'description': 'Freshly pressed watermelon juice served chilled.',
                'ingredients': 'Watermelon, lime, mint.',
                'history': 'Fresh fruit juices are staple refreshments in warm climates around the world.',
                'country_of_origin': 'India',
            },
            {
                'category': cold,
                'name': 'Mango Lassi',
                'slug': 'mango-lassi',
                'brand': 'Desi Dairy',
                'price': 430.80,
                'description': 'Traditional Indian yogurt drink blended with ripe mango.',
                'ingredients': 'Yogurt, mango pulp, sugar, cardamom.',
                'history': 'Lassi is a yogurt-based drink from the Indian subcontinent, enjoyed for centuries in sweet and salty forms.',
                'country_of_origin': 'India',
            },
            {
                'category': cold,
                'name': 'Coconut Water',
                'slug': 'coconut-water',
                'brand': 'Island Fresh',
                'price': 286.80,
                'description': 'Naturally hydrating tender coconut water served chilled.',
                'ingredients': 'Tender coconut water.',
                'history': 'Coconut water has long been consumed in tropical regions as a natural electrolyte drink.',
                'country_of_origin': 'Sri Lanka',
            },
            {
                'category': cold,
                'name': 'Cold Brew Coffee',
                'slug': 'cold-brew-coffee',
                'brand': 'Slow Drip',
                'price': 502.80,
                'description': 'Smooth, slow-brewed coffee concentrate served over ice.',
                'ingredients': 'Coffee, water, ice.',
                'history': 'Cold brew coffee, steeped for many hours, became a specialty café staple in the 21st century.',
                'country_of_origin': 'Japan',
            },
            # Soft drinks
            {
                'category': soft,
                'name': 'Classic Cola',
                'slug': 'classic-cola',
                'brand': 'ColaCo',
                'price': 358.80,
                'description': 'The original cola flavor with a perfect balance of sweetness and fizz.',
                'ingredients': 'Carbonated water, high fructose corn syrup, caramel color, phosphoric acid, natural flavors, caffeine.',
                'history': 'Cola was invented in the late 19th century in the United States. It became a global phenomenon in the 20th century.',
                'country_of_origin': 'USA',
                'featured': True,
            },
            {
                'category': soft,
                'name': 'Orange Soda',
                'slug': 'orange-soda',
                'brand': 'Fizz',
                'price': 334.80,
                'description': 'Bright, citrusy orange flavor in every sip.',
                'ingredients': 'Carbonated water, sugar, citric acid, orange flavor, beta-carotene.',
                'history': 'Orange sodas became popular in America in the mid-20th century alongside other fruit-flavored soft drinks.',
                'country_of_origin': 'USA',
            },
            {
                'category': soft,
                'name': 'Ginger Ale',
                'slug': 'ginger-ale',
                'brand': 'Dry & Crisp',
                'price': 394.80,
                'description': 'Crisp, dry ginger ale with real ginger extract.',
                'ingredients': 'Carbonated water, sugar, ginger extract, citric acid, natural flavors.',
                'history': 'Ginger ale originated in Ireland and Canada in the 19th century. It was often used as a stomach soother.',
                'country_of_origin': 'Canada',
            },
            {
                'category': soft,
                'name': 'Diet Cola',
                'slug': 'diet-cola',
                'brand': 'ColaCo Light',
                'price': 358.80,
                'description': 'Sugar-free cola with the same classic flavor.',
                'ingredients': 'Carbonated water, sweeteners, caramel color, phosphoric acid, natural flavors, caffeine.',
                'history': 'Diet colas were introduced in the mid-20th century as low-calorie alternatives to regular cola.',
                'country_of_origin': 'USA',
            },
            {
                'category': soft,
                'name': 'Lemon-Lime Soda',
                'slug': 'lemon-lime-soda',
                'brand': 'Citrus Fizz',
                'price': 334.80,
                'description': 'Crisp, clear lemon-lime flavored soda.',
                'ingredients': 'Carbonated water, sugar, citric acid, natural lemon and lime flavors.',
                'history': 'Lemon-lime sodas became popular globally as light, caffeine-free alternatives to darker colas.',
                'country_of_origin': 'USA',
            },
            {
                'category': soft,
                'name': 'Grape Soda',
                'slug': 'grape-soda',
                'brand': 'Purple Pop',
                'price': 334.80,
                'description': 'Sweet purple soda with classic grape flavor.',
                'ingredients': 'Carbonated water, sugar, grape flavor, citric acid, color.',
                'history': 'Grape-flavored sodas emerged in the early 20th century alongside other fruit soft drinks.',
                'country_of_origin': 'USA',
            },
            {
                'category': soft,
                'name': 'Root Beer',
                'slug': 'root-beer',
                'brand': 'Old Barrel',
                'price': 370.80,
                'description': 'Traditional root beer with notes of sassafras and vanilla.',
                'ingredients': 'Carbonated water, sugar, root extracts, spices, vanilla.',
                'history': 'Root beer originated in North America and was originally made from foraged roots and herbs.',
                'country_of_origin': 'USA',
            },
            {
                'category': soft,
                'name': 'Tonic Water',
                'slug': 'tonic-water',
                'brand': 'Quinine Co.',
                'price': 358.80,
                'description': 'Bitter tonic water with quinine, perfect as a mixer or on its own.',
                'ingredients': 'Carbonated water, sugar, citric acid, quinine, natural flavors.',
                'history': 'Tonic water was developed as a way to make quinine more palatable for malaria prevention in tropical colonies.',
                'country_of_origin': 'UK',
            },
            {
                'category': soft,
                'name': 'Energy Drink Classic',
                'slug': 'energy-drink-classic',
                'brand': 'ChargeUp',
                'price': 430.80,
                'description': 'High-caffeine energy drink with taurine and B-vitamins.',
                'ingredients': 'Carbonated water, sugar, caffeine, taurine, B-vitamins, flavorings.',
                'history': 'Modern energy drinks were popularized in the late 20th century, inspired by tonics and sports beverages.',
                'country_of_origin': 'Austria',
            },
            {
                'category': soft,
                'name': 'Club Soda',
                'slug': 'club-soda',
                'brand': 'Bar Classic',
                'price': 262.80,
                'description': 'Plain carbonated water with added minerals, ideal as a mixer.',
                'ingredients': 'Carbonated water, sodium bicarbonate, potassium sulfate.',
                'history': 'Club soda emerged as an artificial alternative to naturally sparkling mineral waters.',
                'country_of_origin': 'Ireland',
            },
            # Wines
            {
                'category': wines,
                'name': 'Cabernet Sauvignon',
                'slug': 'cabernet-sauvignon-reserve',
                'brand': 'Vineyard Reserve',
                'price': 2998.80,
                'description': 'Full-bodied red with notes of blackcurrant, cedar, and vanilla.',
                'ingredients': 'Cabernet Sauvignon grapes.',
                'history': 'Cabernet Sauvignon originated in Bordeaux, France. It is now grown in wine regions worldwide.',
                'country_of_origin': 'France',
                'alcohol_percentage': 13.5,
                'featured': True,
            },
            {
                'category': wines,
                'name': 'Chardonnay',
                'slug': 'chardonnay-oaked',
                'brand': 'Valley Winery',
                'price': 2278.80,
                'description': 'Buttery, oaked Chardonnay with apple and vanilla notes.',
                'ingredients': 'Chardonnay grapes.',
                'history': 'Chardonnay is a green-skinned grape from Burgundy, France. It is one of the most planted white varieties.',
                'country_of_origin': 'USA',
                'alcohol_percentage': 13.0,
                'featured': True,
            },
            {
                'category': wines,
                'name': 'Rosé',
                'slug': 'rose-provence',
                'brand': 'Provence Estate',
                'price': 2038.80,
                'description': 'Dry, pale rosé with strawberry and citrus notes.',
                'ingredients': 'Grenache, Cinsault, Syrah grapes.',
                'history': 'Rosé has been made for centuries. Provence-style pale, dry rosé became globally popular in the 21st century.',
                'country_of_origin': 'France',
                'alcohol_percentage': 12.0,
            },
            {
                'category': wines,
                'name': 'Prosecco',
                'slug': 'prosecco-sparkling',
                'brand': 'Veneto Bubbles',
                'price': 1798.80,
                'description': 'Light, fruity Italian sparkling wine.',
                'ingredients': 'Glera grapes.',
                'history': 'Prosecco comes from the Veneto region of Italy. It has been produced since the 19th century.',
                'country_of_origin': 'Italy',
                'alcohol_percentage': 11.0,
            },
            {
                'category': wines,
                'name': 'Pinot Noir',
                'slug': 'pinot-noir',
                'brand': 'Burgundy Hills',
                'price': 2518.80,
                'description': 'Elegant red wine with flavors of cherry, raspberry, and subtle earthiness.',
                'ingredients': 'Pinot Noir grapes.',
                'history': 'Pinot Noir has been grown in Burgundy, France, for centuries and is known as a delicate, terroir-driven grape.',
                'country_of_origin': 'France',
                'alcohol_percentage': 13.0,
            },
            {
                'category': wines,
                'name': 'Sauvignon Blanc',
                'slug': 'sauvignon-blanc',
                'brand': 'Marlborough Estate',
                'price': 2158.80,
                'description': 'Crisp white wine with notes of citrus, gooseberry, and fresh herbs.',
                'ingredients': 'Sauvignon Blanc grapes.',
                'history': 'Sauvignon Blanc originated in France and became world-famous through New Zealand’s intensely aromatic style.',
                'country_of_origin': 'New Zealand',
                'alcohol_percentage': 12.5,
            },
            {
                'category': wines,
                'name': 'Riesling',
                'slug': 'riesling',
                'brand': 'Mosel Valley',
                'price': 1918.80,
                'description': 'Aromatic white wine with floral notes, stone fruit, and lively acidity.',
                'ingredients': 'Riesling grapes.',
                'history': 'Riesling is a classic grape from Germany’s Rhine and Mosel regions, prized for its aging potential.',
                'country_of_origin': 'Germany',
                'alcohol_percentage': 11.5,
            },
            {
                'category': wines,
                'name': 'Malbec',
                'slug': 'malbec-reserva',
                'brand': 'Andes Reserve',
                'price': 2278.80,
                'description': 'Rich Argentinian red with dark fruit, cocoa, and spice notes.',
                'ingredients': 'Malbec grapes.',
                'history': 'Originally from France, Malbec found a new home in Argentina, where it became the country’s signature red wine.',
                'country_of_origin': 'Argentina',
                'alcohol_percentage': 13.5,
            },
            {
                'category': wines,
                'name': 'Champagne Brut',
                'slug': 'champagne-brut',
                'brand': 'Maison de Reims',
                'price': 3598.80,
                'description': 'Traditional method sparkling wine from Champagne with fine bubbles and brioche notes.',
                'ingredients': 'Chardonnay, Pinot Noir, Pinot Meunier grapes.',
                'history': 'Champagne became associated with celebration in the 18th and 19th centuries, produced exclusively in the Champagne region of France.',
                'country_of_origin': 'France',
                'alcohol_percentage': 12.0,
            },
            {
                'category': wines,
                'name': 'Port Wine',
                'slug': 'ruby-port',
                'brand': 'Douro Cellars',
                'price': 2398.80,
                'description': 'Sweet fortified wine with rich berry flavors and warming finish.',
                'ingredients': 'Traditional Portuguese grape varieties, grape spirit.',
                'history': 'Port is a fortified wine from Portugal’s Douro Valley, exported worldwide since the 17th century.',
                'country_of_origin': 'Portugal',
                'alcohol_percentage': 19.0,
            },            # Tea
            {
                'category': tea,
                'name': 'Green Tea',
                'slug': 'green-tea-matcha',
                'brand': 'Zen Garden',
                'price': 480.80,
                'description': 'Unoxidized, light, and grassy green tea with fresh vegetal notes.',
                'ingredients': 'Green tea leaves, Matcha powder.',
                'history': 'Green tea has been consumed in Asia for millennia. Matcha became popular in Japan as a ceremonial tea.',
                'country_of_origin': 'Japan',
                'featured': True,
            },
            {
                'category': tea,
                'name': 'Black Tea Assam',
                'slug': 'black-tea-assam',
                'brand': 'Colonial Estate',
                'price': 520.80,
                'description': 'Fully oxidized bold black tea with malty, robust flavor from Assam region.',
                'ingredients': 'Assam black tea leaves.',
                'history': 'Assam tea comes from the Assam region of India and is prized for its strong, malty character.',
                'country_of_origin': 'India',
            },
            {
                'category': tea,
                'name': 'Black Tea Darjeeling',
                'slug': 'black-tea-darjeeling',
                'brand': 'Highland Peak',
                'price': 598.80,
                'description': 'Muscatel-floral black tea from the foothills of the Himalayas.',
                'ingredients': 'Darjeeling black tea leaves.',
                'history': 'Darjeeling tea is called the "champagne of teas" due to its delicate, fruity flavor and floral aroma.',
                'country_of_origin': 'India',
                'featured': True,
            },
            {
                'category': tea,
                'name': 'Earl Grey',
                'slug': 'earl-grey-black-tea',
                'brand': 'Classic Blend',
                'price': 540.80,
                'description': 'Black tea infused with bergamot oil for a distinctive citrusy flavor.',
                'ingredients': 'Black tea, bergamot oil, natural flavors.',
                'history': 'Earl Grey was named after Charles, 2nd Earl Grey, and became an iconic British afternoon tea blend.',
                'country_of_origin': 'UK',
            },
            {
                'category': tea,
                'name': 'Oolong Tea',
                'slug': 'oolong-tea',
                'brand': 'Mountain Selection',
                'price': 560.80,
                'description': 'Partially oxidized tea with complex flavor ranging from light and floral to rich and buttery.',
                'ingredients': 'Oolong tea leaves.',
                'history': 'Oolong tea originated in China and Taiwan. Its oxidation level is carefully controlled for unique flavor profiles.',
                'country_of_origin': 'Taiwan',
            },
            {
                'category': tea,
                'name': 'White Tea',
                'slug': 'white-tea',
                'brand': 'Silvertip Estate',
                'price': 480.80,
                'description': 'Minimally processed tea with subtle, sweet flavor and delicate aroma.',
                'ingredients': 'White tea leaves.',
                'history': 'White tea is the least processed tea, preserving more antioxidants. It originated in Fujian Province, China.',
                'country_of_origin': 'China',
            },
            {
                'category': tea,
                'name': 'Herbal Tea Chamomile',
                'slug': 'herbal-tea-chamomile',
                'brand': 'Calming Brew',
                'price': 380.80,
                'description': 'Caffeine-free soothing chamomile flowers with gentle apple-like notes.',
                'ingredients': 'Dried chamomile flowers, natural flavors.',
                'history': 'Chamomile has been used for centuries in herbal teas for relaxation and digestive benefits.',
                'country_of_origin': 'Egypt',
            },
            {
                'category': tea,
                'name': 'Herbal Tea Peppermint',
                'slug': 'herbal-tea-peppermint',
                'brand': 'Fresh Mint',
                'price': 390.80,
                'description': 'Refreshing caffeine-free peppermint infusion with cooling menthol notes.',
                'ingredients': 'Dried peppermint leaves.',
                'history': 'Peppermint tea has been enjoyed for digestive and cooling benefits since ancient times.',
                'country_of_origin': 'USA',
            },
            {
                'category': tea,
                'name': 'Pu\'erh Tea',
                'slug': 'puerh-tea',
                'brand': 'Aged Reserve',
                'price': 620.80,
                'description': 'Fermented and aged tea with deep, earthy flavor and smooth, slightly sweet finish.',
                'ingredients': 'Pu\'erh tea leaves.',
                'history': 'Pu\'erh tea from Yunnan, China, is fermented and aged for depth. It was historically used as currency.',
                'country_of_origin': 'China',
            },
            # Coffee
            {
                'category': coffee,
                'name': 'Arabica Coffee',
                'slug': 'arabica-coffee',
                'brand': 'Mountain Peaks',
                'price': 480.80,
                'description': 'Smooth, complex coffee known for slightly acidic taste and refined flavor notes.',
                'ingredients': 'Arabica coffee beans.',
                'history': 'Arabica is the most popular coffee species, accounting for about 60% of world coffee production.',
                'country_of_origin': 'Ethiopia',
                'featured': True,
            },
            {
                'category': coffee,
                'name': 'Robusta Coffee',
                'slug': 'robusta-coffee',
                'brand': 'Strong Brew',
                'price': 420.80,
                'description': 'Strong, bitter coffee with higher caffeine content and bold, earthy flavors.',
                'ingredients': 'Robusta coffee beans.',
                'history': 'Robusta is hardier and higher in caffeine than Arabica. It\'s used in espresso blends and instant coffee.',
                'country_of_origin': 'Vietnam',
            },
            {
                'category': coffee,
                'name': 'Espresso',
                'slug': 'espresso-blend',
                'brand': 'Intense Roast',
                'price': 480.80,
                'description': 'Concentrated, intense coffee made by forcing hot water through finely ground beans.',
                'ingredients': 'Espresso blend coffee beans (Arabica and Robusta mix).',
                'history': 'Espresso was invented in Italy in the early 20th century and became the foundation of modern coffee culture.',
                'country_of_origin': 'Italy',
                'featured': True,
            },
            {
                'category': coffee,
                'name': 'Cold Brew Coffee Premium',
                'slug': 'cold-brew-premium',
                'brand': 'Smooth Steep',
                'price': 520.80,
                'description': 'Smooth, less acidic coffee steeped in cold water for 12+ hours, perfect served over ice.',
                'ingredients': 'Premium Arabica coffee beans, cold water.',
                'history': 'Cold brew became popular in specialty coffee shops as a method to reduce acidity and bring out smooth flavors.',
                'country_of_origin': 'USA',
            },
            {
                'category': coffee,
                'name': 'Turkish Coffee',
                'slug': 'turkish-coffee',
                'brand': 'Ottoman Gold',
                'price': 420.80,
                'description': 'Unfiltered, strong, finely ground coffee boiled in a traditional cezve pot.',
                'ingredients': 'Finely ground Turkish coffee beans.',
                'history': 'Turkish coffee is an ancient brewing method dating back 500+ years. It\'s prepared in a special pot called a cezve or ibrik.',
                'country_of_origin': 'Turkey',
            },        ]

        for data in products_data:
            Product.objects.update_or_create(
                slug=data['slug'],
                defaults=data
            )

        self.stdout.write(self.style.SUCCESS(
            f'Created/updated {len(products_data)} products and 5 categories.'
        ))
