# Generated by Django 4.2.28 on 2026-02-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='volume',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
